### ISSUE TITLE
汎用的なものが登録できるツールが欲しいです

### ISSUE THREAD

**Issue by Megumi-N** [dadajam4/fastkit#19]
### Target Packages

@fastkit/vui-wysiwyg

### Description

WysiwygBulletListToolなどのように注記用のツールが欲しいなと思っているのですが、任意の機能が登録できる汎用的なツールがほしいです。

### What problem does this feature solve?

フォントの大きさを変えたくない時でも、本文より小さい文字で表現できるため、注記のような小さく表現したいということが叶えられます。

### Proposed Solution or API

.

**Comment by dadajam4** [comment]
@Megumi-N 

カスタムタグ用のツールを生成するジェネレータを追加しました。

https://github.com/dadajam4/fastkit/pull/22

以下で動作を確認できます。

https://dadajam4.github.io/fastkit/ja/vui/components/wysiwygs

設置方法はこちらを参考にしてください。

https://github.com/dadajam4/fastkit/pull/22/files#diff-4defade2d40e9add44f7bad16a7d2eb55bc3db071a06dec3eee5817e4b1a80d8R57-R63
