### ISSUE TITLE
text-alignのツールが欲しいです

### ISSUE THREAD

**Issue by Megumi-N** [dadajam4/fastkit#4]
こんにちは。

業務でWysiwyFormatを使用しているのですが、テキストの配置についてのツールが必要になりました。
WysiwyFormatでtext-alignの機能が欲しいです。

![スクリーンショット 2023-04-07 17 28 45](https://user-images.githubusercontent.com/64998512/230573093-372920cc-8918-4b62-be1f-1d38009e490a.jpg)

よろしくお願いします。

**Comment by dadajam4** [comment]
@Megumi-N

[@fastkit/vui-wysiwyg@1.0.1](https://www.npmjs.com/package/@fastkit/vui-wysiwyg) で追加されました。

こちらで動作が確認できます。
https://dadajam4.github.io/fastkit/ja/vui/components/wysiwygs
